### ISSUE TITLE
Add ability to play VNC via novnc

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid-ui#10]
Having:
1) A ready to use in-browser VNC client: https://github.com/novnc/noVNC
2) Selenoid support for proxying container VNC port (https://github.com/aerokube/selenoid/issues/52)
Need to somehow show this client in UI.

**Comment by lanwen** [comment]
some links
https://engineering.linkedin.com/javascript/vncjs-how-build-javascript-vnc-client-24-hour-hackday
https://www.infoq.com/news/2010/07/html5-novnc
http://blog.mgechev.com/2013/08/30/vnc-javascript-nodejs/
https://github.com/bgaff/vnc.js
https://github.com/mgechev/js-vnc-demo-project
