### ISSUE TITLE
Feature Request. Custom title.

### ISSUE THREAD

**Issue by tymfear** [aerokube/selenoid-ui#102]
Add CLI flag for custom title of the webUi.
Then provide the title to the page to be displayed on browser's tab and also somewhere in UI.
When having several Selenoid-UIs on several machines, that would ease switching between them.

**Comment by lanwen** [comment]
Probably it can just reflect the hostname without any cli args

**Comment by tymfear** [comment]
@lanwen well, yeah, it can! But it won't be useful when you got IPs as host names.
Unless you remember all the IPs :-p

**Comment by lanwen** [comment]
Is that still actual with ggr-ui existence?
