### ISSUE TITLE
[Feature Request] Add a way to send the terminate signal to container from UI.

### ISSUE THREAD

**Issue by tymfear** [aerokube/selenoid-ui#105]
CUrrently when I run my specs from local machine against GGR, if I want to stop test execution, I should wait until current tests are finished, even if I stopped them locally. 
It would be nice to have some button to click to terminate test execution and stop container.
Also it would be cool to secure the element with password or permissions.

**Comment by vania-pooh** [comment]
@tymfear tests can be run on a separate host. How would you stop a process on a separate host?

**Comment by tymfear** [comment]
Well, cannot tell exactly, but, maybe by some API call. It's more like - `It would be nice to have, if it is technically possible.`

**Comment by vania-pooh** [comment]
@tymfear ok, agreed.

**Comment by lanwen** [comment]
we should call `curl -X DELETE http://localhost:9515/session/27f4262ab044392b05138540055a8fd6`
