### ISSUE TITLE
[Feature request] Possibility to start new sessions for manual testing

### ISSUE THREAD

**Issue by vgrigoruk** [aerokube/selenoid-ui#114]
It would be quite convenient to have a possibility of starting a new browser session directly in selenoid-ui (and then work with a browser via VNC session directly in selenoid-ui). 
This could be used for manual tests / troubleshooting issues with automated tests in specific browser versions (replicate Saucelabs "manual testing" feature)

Preconditions:
- Browser images with VNC should be used.
- Figure out what to do if `selenoid-ui` is used with `ggr-ui / ggr`, as creating a new session requires username/password.

**Comment by vania-pooh** [comment]
Ok. Will consider such feature.
