### ISSUE TITLE
Getting Device not configured with verion 1.7.0

### ISSUE THREAD

**Issue by marcelcandidoferreira** [aerokube/selenoid-ui#117]
I'm getting `Device not configured` with the new version 1.7.0.

The version from 5 days ago was totally fine...

**Comment by vania-pooh** [comment]
@marcelcandidoferreira I don't get where is the error. Could you e.g. attach some screenshot.

**Comment by marcelcandidoferreira** [comment]
Docker instance: 

![image](https://user-images.githubusercontent.com/15752746/43038097-b127ee80-8ce1-11e8-99c6-2e0639ee14c2.png)

**Comment by marcelcandidoferreira** [comment]
@vania-pooh Is there a way to run with a previous version to test and confirm?

**Comment by vania-pooh** [comment]
@marcelcandidoferreira just use another image, e.g. `aerokube/selenoid:1.6.2` or another version from [releases page](https://github.com/aerokube/selenoid/releases).

**Comment by marcelcandidoferreira** [comment]
When I download the previous cm (binarie) version 1.5.0 and run it, the docker image created is aerokube/selenoid:1.7.0

Probably all the biaries will use the lastest docker image? Also using the cm 1.4.2, the docker instance created was aerokube/selenoid:1.7.0

* in all the cases, still the same error.

This folder should contain the chromedriver no?
![image](https://user-images.githubusercontent.com/15752746/43039599-9999e846-8cfe-11e8-9a32-07732d24dca1.png)


any other idea?

**Comment by vania-pooh** [comment]
@marcelcandidoferreira ah, ok. You have to run a command like this with CM:
```
$ ./cm selenoid start --vnc --version 1.6.2
```

**Comment by marcelcandidoferreira** [comment]
Same error running with aerokube/selenoid:1.6.2 . Weird cause I was able to run it last Sunday, very easily.

**Comment by marcelcandidoferreira** [comment]
Bingo, I was exactly search form --force command. It seems for some reasons the drivers wasn't installed anymore here in my pc. I did a test in other computer and I saw downloading the drivers but in my pc I didnt. Using force I saw it again in my PC and everything started working again.

**Comment by vania-pooh** [comment]
@marcelcandidoferreira yes, by default `cm` does not overwrite `browsers.json` file and considers everything configured when this file exists. `--force` flag allows to override this behavior.
