### ISSUE TITLE
selenoid+selenoid-ui and ggr+nginx

### ISSUE THREAD

**Issue by kiam123** [aerokube/selenoid-ui#122]
selenoid+selenoid-ui i do this, but image error

![image](https://user-images.githubusercontent.com/14953180/43356913-b0698bb4-92ab-11e8-953a-7ca5e9309429.png)
`browser.json`
```shell=
{
    "chrome": {
        "default": "67.0",
        "versions": {
            "66.0": {
                "image": "selenoid/vnc_chrome:66.0",
                "port": "4444",
                "path": "/"
            },
            "67.0": {
                "image": "selenoid/vnc_chrome:67.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
    "firefox": {
        "default": "61.0",
        "versions": {
            "60.0": {
                "image": "selenoid/vnc_firefox:60.0",
                "port": "4444",
                "path": "/wd/hub"
            },
            "61.0": {
                "image": "selenoid/vnc_firefox:61.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    },
    "opera": {
        "default": "54.0",
        "versions": {
            "53.0": {
                "image": "selenoid/vnc_opera:53.0",
                "port": "4444",
                "path": "/"
            },
            "54.0": {
                "image": "selenoid/vnc_opera:54.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}
```
`docker-compose.yml`
```shell=
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.7.1"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.6.1"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```
![image](https://user-images.githubusercontent.com/14953180/43357167-f8672440-92af-11e8-9af6-de8c2f569918.png)

**Comment by kiam123** [comment]
ggr+nginx i do this
docker-compose.yml
```shell=
version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    depends_on:
    - ggr
    ports:
    - 4445:4445
    restart: unless-stopped
    volumes:
    - ./etc/nginx/conf.d/ggr.conf:/etc/nginx/conf.d/ggr.conf:ro

  ggr:
    image: aerokube/ggr:latest-release
    ports:
    - 5555:5555
    restart: unless-stopped
    volumes:
    - ./etc/grid-router:/etc/grid-router:ro
    command: ["-listen", ":5555"]
```shell=
ggr.conf
upstream ggr {
  server xxx.xxx.xx.xx:5555 weight=10  max_fails=3 fail_timeout=10s;
}
server {
  server_name www.ggr.com;
  location / {
    proxy_pass http://ggr;
  }
}
```
test.xml
```shell=
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="66.0">
	<version number="66.0" platform="LINUX">
        <region name="Taiwan">
            <host name="xxx.xxx.xx.xx" port="4444" count="1"/>        
        </region>
	</version>
</browser>
</qa:browsers>
```
![image](https://user-images.githubusercontent.com/14953180/43357254-2abfd3d2-92b1-11e8-823d-666b55b715d8.png)

**Comment by kiam123** [comment]
images error how to fix this problem?

**Comment by vania-pooh** [comment]
@kiam123 linking error happens because Selenoid fails to start. I think this is because you current directory does not contain `browsers.json`.

**Comment by kiam123** [comment]
nice, i fix the problem.
Now my computer can check the status `"curl http://localhost:4444/status"`, but the external computer can't connect to my server status `"xxx.xxx.xx.xx:4444/status"`

![image](https://user-images.githubusercontent.com/14953180/43360165-fb9d43d2-92e2-11e8-83df-3fa338411548.png)

![image](https://user-images.githubusercontent.com/14953180/43360116-574baab2-92e2-11e8-9441-2c4aa2bda344.png)

**Comment by aandryashin** [comment]
Most probably firewall does not allow to connect from external sources.

2018-07-28 22:54 GMT+03:00 kr lee <notifications@github.com>:

**Comment by kiam123** [comment]
but i can connect selenoid ui `"my_server_ip:8080"` , can not connect selenoid status `"my_server_ip:4444/status"`

![image](https://user-images.githubusercontent.com/14953180/43363581-56727dca-933a-11e8-99fb-7b3dcf9779a8.png)

**Comment by kiam123** [comment]
@aandryashin 
![image](https://user-images.githubusercontent.com/14953180/43364290-1046a046-934a-11e8-8a20-71be2c5a0260.png)

**Comment by kiam123** [comment]
@vania-pooh 
thank you, i change 8082:4444 fix this problem, i think is my school is block 4444 this port.
Now if i can use docker-compose set up container limit/memory/cpu? because use `selenoid` software type `$ ./selenoid start --args "-limit 10"` can set up 10 containers

**Comment by vania-pooh** [comment]
@kiam123 take a look at the following Selenoid args:
```
-cpu value
    Containers cpu limit as float e.g. 0.2 or 1.0
-mem value
    Containers memory limit e.g. 128m or 1g
```

**Comment by kiam123** [comment]
@vania-pooh What is missing from my GGR? Can not load banlancing

![image](https://user-images.githubusercontent.com/14953180/43384593-10e3b850-9411-11e8-896b-5dec223f85aa.png)


**windows do ggr, linux do selenoid**
ggr `docker-compose.yml` file
```shell=
version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    depends_on:
    - ggr
    ports:
    - 4444:4444
    restart: unless-stopped
    volumes:
    - ./etc/nginx/conf.d/ggr.conf:/etc/nginx/conf.d/ggr.conf:ro

  ggr:
    image: aerokube/ggr:latest-release
    ports:
    - 5555:5555
    restart: unless-stopped
    volumes:
    - ./etc/grid-router:/etc/grid-router:ro
    command: ["-listen", ":5555"]
```
`ggr.conf`
```shell=
upstream ggr {
  server my_selenod_ip:5555 weight=10  max_fails=3 fail_timeout=10s;
}
server {

  listen 4444 default_server;
  listen [::]:4444 default_server;

  location / {
    proxy_pass http://ggr;
  }

}
```
`test.xml`
```shell=
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="chrome" defaultVersion="66.0">
	<version number="66.0" platform="LINUX">
        <region name="Taiwan">
            <host name="my_selenod_ip" port="8082" count="5"/>        
        </region>
	</version>
</browser>
</qa:browsers>
```

**Comment by vania-pooh** [comment]
@kiam123 you are requesting `Chrome 66.0` in your tests and does no have such browser name and version in quota XML file. You could try to remove `platform` attribute and see whether it helps.

**Comment by vania-pooh** [comment]
@kiam123 take a look at Selenoid logs using `docker logs selenoid`. There should be an error message inside. Right now Ggr tries to create a session but for some reason Selenoid fails to do this. Did you pull respective images?

**Comment by kiam123** [comment]
@vania-pooh sry is my fault, I did not open selenoid.
sorry, I have a problem again. I have been looking for this problem myself `https://github.com/docker/for-win/issues/1829`. I need to use COMPOSE_CONVERT_WINDOWS_PATHS=1 but I still can't solve it.

```shell=
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.7.1"
    network_mode: bridge
    ports:
      - "8082:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.6.1"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```

![image](https://user-images.githubusercontent.com/14953180/43409194-d3d65c84-9455-11e8-8fee-b718932aead8.png)

**Comment by vania-pooh** [comment]
@kiam123 in Windows mount should be `- "//var/run/docker.sock:/var/run/docker.sock"` (with 2 slashes at the beginning).

**Comment by kiam123** [comment]
@vania-pooh  same the problem
![image](https://user-images.githubusercontent.com/14953180/43410710-66c9cb30-945a-11e8-96fe-3d2e8e4075a7.png)

**Comment by kiam123** [comment]
@vania-pooh  i fix this problem, create `.env' inside type `COMPOSE_CONVERT_WINDOWS_PATHS=1`

**Comment by vania-pooh** [comment]
@kiam123 is this issue now resolved?

**Comment by kiam123** [comment]
@vania-pooh The last problem I have is to set up multiple selenoid container, memory, cpu usage, but I am still trying to set it, because I am not familiar with docker, so I am still researching.

**Comment by kiam123** [comment]
@vania-pooh You taught me cpu, memory, but didn't teach me how to set up multiple containers.

```shell=
-cpu value
    Containers cpu limit as float e.g. 0.2 or 1.0
-mem value
    Containers memory limit e.g. 128m or 1g
```

**Comment by vania-pooh** [comment]
@kiam123 e.g. `./cm selenoid start --args "-limit 50 -cpu 1.0 -mem 500m"`.

**Comment by kiam123** [comment]
can not use docker-compose do this command?

`docker-compose.yml`
```shell=
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.7.1"
    network_mode: bridge
    ports:
      - "8082:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "//var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.6.1"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```

**Comment by kiam123** [comment]
i do not how insert `args` to `docker-compose.yml`

like this?
```shell=
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.7.1"
    args:
        -limit 50
    network_mode: bridge
    ports:
      - "8082:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.6.1"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
```

**Comment by vania-pooh** [comment]
@kiam123 section is called `command` in `docker-compose`.

**Comment by kiam123** [comment]
@vania-pooh I wrote two and I can't change it.
```shell=
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.7.1"
    network_mode: bridge
    ports:
      - "8082:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["start", "--args", "-limit", "50"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.6.1"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444" ]
```
![image](https://user-images.githubusercontent.com/14953180/43458462-f3768800-94fc-11e8-8f13-a8634c10909e.png)
![image](https://user-images.githubusercontent.com/14953180/43458527-2188b268-94fd-11e8-845b-9e4a77d43982.png)


```shell=
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.7.1"
    network_mode: bridge
    ports:
      - "8082:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.6.1"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444", "start", "--args", "-limit", "50"]
```
![image](https://user-images.githubusercontent.com/14953180/43458505-1465a32a-94fd-11e8-8b1d-d85b5db096de.png)
![image](https://user-images.githubusercontent.com/14953180/43458530-22add466-94fd-11e8-94ca-0c5b7578e2c2.png)

**Comment by vania-pooh** [comment]
@kiam123 should be like this:
```
version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.7.1"
    network_mode: bridge
    ports:
      - "8082:4444"
    volumes:
      - ".:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-limit", "50", "-cpu", "1.0", "-mem", "512m"]
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.6.1"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444" ]
```

**Comment by kiam123** [comment]
@vania-pooh  Thank you very much, because there are a lot of things that won’t bother you.This issue can close
