### ISSUE TITLE
Selenoid unable to connect to ggr-ui

### ISSUE THREAD

**Issue by rohitpatwari84** [aerokube/selenoid-ui#127]
Today all of a sudden I started seeing the below errors on starting selenoid ui .Not sure what these errors are about - 

```
selenoid-ui_1  | 2018/09/16 18:12:01 can't get status (Get http://ggr-ui:8888/status: context deadline exceeded)
selenoid-ui_1  | 2018/09/16 18:12:01 can't get status (Get http://ggr-ui:8888/status: context deadline exceeded)
```

**Comment by tymfear** [comment]
Chances are that one or more hosts does not answer and selenoid-ui fails. This issue bothers me for 4 months already. So check if all selenoid hosts from your quota are up and running.

**Comment by rohitpatwari84** [comment]
Hmm..So is there no workaround for that ? It is an issue because if there is any problem with any host then I wont be able to connect to selenoid ui. Removing the host entry from user.xml seems to be a bad option

**Comment by tymfear** [comment]
Welcome to the club!

**Comment by aandryashin** [comment]
actually it is already fixed, please make sure, that you are using latest
ggr-ui version.

вс, 16 сент. 2018 г., 21:27 tymfear <notifications@github.com>:

**Comment by rohitpatwari84** [comment]
I guess I am using latest version - 

![image](https://user-images.githubusercontent.com/41872833/45643301-65e4dd00-bad8-11e8-9d40-bf2c5edc68be.png)

**Comment by aandryashin** [comment]
Please try to repull image...

пн, 17 сент. 2018 г., 21:48 rohitpatwari84 <notifications@github.com>:

**Comment by rohitpatwari84** [comment]
Thanks Alex . By repull do you mean delete image and pull the latest image again?

**Comment by vania-pooh** [comment]
@rohitpatwari84 just do:
```
# docker pull aerokube/ggr-ui:latest-release
```
This can solve your problem because `latest-release` tag is pointing to latest release in Docker Hub only. You still have to periodically pull the image again to update versions.

**Comment by lanwen** [comment]
should be fixed with latest ggr-ui, feel free to reopen if issue still there
