### ISSUE TITLE
Ability to show capabilities for all available browsers

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid-ui#13]
Currently it's not really clear how to launch browser.

**Comment by lanwen** [comment]
Maybe also show some examples for different langs? Some kind of quick-start helper...

**Comment by vania-pooh** [comment]
@lanwen the minimal implementation is to show just:
```
browserName = firefox
version = 53.0
platform = LINUX
```
An advanced implementation is to show series of tabs corresponding to different langs. I would only show officially supported Selenium langs:
* Java
* Python
* C#
* Ruby
* Javascript (which one of 100500 existing implementations is suitable)
