### ISSUE TITLE
Is it possible somehow to look at browser console via selenoid ui for debugging?

### ISSUE THREAD

**Issue by EdgarGalstyan** [aerokube/selenoid-ui#135]
Just would like to clarify:

Is it possible somehow to look at browser console via selenoid ui for debugging?

**Comment by vania-pooh** [comment]
@EdgarGalstyan yep, just open it as usually. By default Selenoid UI VNC feature is working in read-only mode (to not accidentally intercept running tests). This can be turned off by clicking on violet button with a padlock icon.

**Comment by EdgarGalstyan** [comment]
Great! 
Thanks Ivan Krutov!)
