### ISSUE TITLE
Custom link in vnc session section

### ISSUE THREAD

**Issue by Quron** [aerokube/selenoid-ui#137]
Hi. Can you added a links support?

Its useful for fast follow to test report or ci build pages
![8e302358c0](https://user-images.githubusercontent.com/26869885/50726545-e844eb80-111f-11e9-94bb-dd94c8f68251.png)

E.g, set capability ```link: "myLinkToJenkinsBuild"``` and we see button with this link

**Comment by lanwen** [comment]
right now we show only a limited subset of the capabilities, explicitly whitelisted in the status handle of the selenoid. So better to start from there and expose all requested capabilities
