### ISSUE TITLE
Incorrect displaying in case that quota file contains more than 11 browsers

### ISSUE THREAD

**Issue by dtuchs** [aerokube/selenoid-ui#138]
We would like to see scroll or correct list scaling, but for now it looks like this:
<img width="1034" alt="2019-01-29 15 45 56" src="https://user-images.githubusercontent.com/25635227/51909212-1b0b9800-23dd-11e9-9f39-c95388aa8c5a.png">

**Comment by lanwen** [comment]
fixed in https://github.com/aerokube/selenoid-ui/pull/142

**Comment by lanwen** [comment]
@dtuchs btw, why don't you use versions of one browser for that?
