### ISSUE TITLE
Release 1.6.4 has no assets

### ISSUE THREAD

**Issue by antonu17** [aerokube/selenoid-ui#140]
## Problem

Hello team!

There are pre-compiled binaries missing for [release v1.6.4](https://github.com/aerokube/selenoid-ui/releases/tag/1.6.4). Is it on purpose or forgotten? Could you please add assets to the release?

Best,
Anton

**Comment by lanwen** [comment]
No worries, just failed build, assets will be available right after fix

**Comment by lanwen** [comment]
fixed in 1.6.5 release
