### ISSUE TITLE
Add option to open automatically the VNC session if there is only one

### ISSUE THREAD

**Issue by istvandesign** [aerokube/selenoid-ui#144]
I am using selenoid just because I want to use my computer while running the tests. It would be nice if I had an option to automatically show the VNC window fullscreen if there is only one session running and this option is activated.

**Comment by lanwen** [comment]
@istvandesign how would you imagine that option, can you describe it more precisely?

**Comment by istvandesign** [comment]
@lanwen Hello, my idea is to have a flip switch near the Starts/Capabilities in the header which when set to ON would open the last created vnc session maximized if there are no others sessions running.
