### ISSUE TITLE
VNC Disconnected

### ISSUE THREAD

**Issue by poii123** [aerokube/selenoid-ui#145]
I am try to launch a selenoid cluster with 5 selenoid hosts, 2 ggr hosts, with one hosts for the dashboard and ggr-ui. Everything works flawlessly except selenoid-ui, I can see the containers with the session name but when I click it to view logs it just says disconnected.

 The selenoid-ui logs:
```4/29/2019 8:48:40 PM2019/04/30 03:48:40 [WS_PROXY] [/ws/vnc/951eaf7617ace5a5e9c232d304ddae07992523c0-d459-456c-9fd9-8cc4671046f2] [ws://selenium-stats:8888/vnc/951eaf7617ace5a5e9c232d304ddae07992523c0-d459-456c-9fd9-8cc4671046f2]
4/29/2019 8:48:40 PM2019/04/30 03:48:40 websocketproxy: couldn't upgrade websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
4/29/2019 8:48:40 PM2019/04/30 03:48:40 [WS_PROXY] [/vnc/951eaf7617ace5a5e9c232d304ddae07992523c0-d459-456c-9fd9-8cc4671046f2] [CLOSED]
``` 

I don't know how to deal with websocketproxy: couldn't upgrade websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header. Your help will be much appreciated.

**Comment by vania-pooh** [comment]
@poii123 usually such issues occur when you put everything behind some reverse proxy, e.g. Nginx. You have to correctly proxy web sockets as Selenoid UI is using them to fetch VNC screen information from `ggr-ui`. Should be something like the following:
```
  location ~ ^/vnc/ {
    proxy_pass http://ggr-ui;
    proxy_http_version 1.1;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
```

**Comment by alexbode** [comment]
I am getting that issue without an nginx proxy, I am just using an AWS elastic load balancer.

**Comment by lanwen** [comment]
assume solved
