### ISSUE TITLE
Cannot view vnc preview

### ISSUE THREAD

**Issue by alexbode** [aerokube/selenoid-ui#146]
I can't view the vnc preview in selenoid-ui even though I can see the logs.

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/25521899/56996963-129d3780-6b5b-11e9-95c4-7d18813454f1.png">

browsers.json:
```{
    "firefox": {
        "default": "66.0",
        "versions": {
            "66.0": {
                "image": "selenoid/firefox:66.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {"/tmp":"size=512m"},
                "cpu" : "1.0",
                "mem" : "512m",
                "shmSize" : 1920000000
            },
            "vnc": {
                "image": "selenoid/vnc:firefox_66.0",
                "port": "4444",
                "path": "/wd/hub",
                "tmpfs": {"/tmp":"size=512m"},
                "cpu" : "1.0",
                "mem" : "512m",
                "shmSize" : 1920000000
            }
        }
    },
    "chrome": {
        "default": "73.0",
        "versions": {
            "73.0": {
                "image": "selenoid/chrome:73.0",
                "port": "4444",
                "tmpfs": {"/tmp":"size=512m"},
                "cpu" : "1.0",
                "mem" : "512m",
                "shmSize" : 1920000000
            },
            "vnc": {
                "image": "selenoid/vnc:chrome_73.0",
                "port": "4444",
                "tmpfs": {"/tmp":"size=512m"},
                "cpu" : "1.0",
                "mem" : "512m",
                "shmSize" : 1920000000
            }
        }
    }
}
```

Container logs:

2019-04-30T22:02:41.222950467Z    "capabilities": {
2019-04-30T22:02:41.222953021Z       "alwaysMatch": {
2019-04-30T22:02:41.222955344Z          "browserName": "chrome",
2019-04-30T22:02:41.222957689Z          "browserVersion": "vnc"
2019-04-30T22:02:41.222960180Z       },
2019-04-30T22:02:41.222962353Z       "firstMatch": [ {
2019-04-30T22:02:41.222964574Z 
2019-04-30T22:02:41.222966656Z       } ]
2019-04-30T22:02:41.222969048Z    },
2019-04-30T22:02:41.222971280Z    "desiredCapabilities": {
2019-04-30T22:02:41.222973416Z       "browserName": "chrome",
2019-04-30T22:02:41.222975744Z       "enableLog": true,
2019-04-30T22:02:41.222977901Z       "enableVNC": true,
2019-04-30T22:02:41.222980117Z       "name": "Session: Testing",
2019-04-30T22:02:41.222982301Z       "sessionTimeout": "30m",
2019-04-30T22:02:41.222984554Z       "version": "vnc"
2019-04-30T22:02:41.222986777Z    }
2019-04-30T22:02:41.222988755Z }

**Comment by vania-pooh** [comment]
@alexbode do you have any reverse-proxy like Nginx in front of Selenoid UI? If so, you have to correctly proxy web-sockets.

**Comment by alexbode** [comment]
I am not using a reverse proxy. 
Is this what you mean by browser developer console?
```4/30/2019 9:12:13 PM2019/05/01 04:12:13 [100] [SESSION_CREATED] [13bdb6ef01c36bf17d526f6cc4babd7a] [1] [0.61s]
4/30/2019 9:13:43 PM2019/05/01 04:13:43 [104] [CONTAINER_LOGS] [2565daa81c4f3a763427708031f49c2aaf1a50ae0304132cf53d278e8816e36f]
4/30/2019 9:13:43 PM2019/05/01 04:13:43 [105] [VNC_ENABLED] [13bdb6ef01c36bf17d526f6cc4babd7a]
4/30/2019 9:13:44 PM2019/05/01 04:13:44 [105] [VNC_CLIENT_DISCONNECTED] [13bdb6ef01c36bf17d526f6cc4babd7a]
4/30/2019 9:13:44 PM2019/05/01 04:13:44 [105] [VNC_SESSION_CLOSED] [13bdb6ef01c36bf17d526f6cc4babd7a]```

**Comment by alexbode** [comment]
Sorry to waste your time but the issue is on my end. I tried to change the 'selenoid' password to vnc into the container. When I use the aerokube/selenoid-ui:latest all is working.

**Comment by vania-pooh** [comment]
@alexbode yes, it is also hard-coded to UI.

**Comment by jmsampayo** [comment]
> do you have any reverse-proxy like Nginx in front of Selenoid UI? If so, you have to correctly proxy web-sockets used to show the VNC screen. Take a look at browser developer console to get the actual reason of the error.

Hi @vania-pooh, I think this is exactly my issue. I'm trying to configure my Selenoid UI instance behind an Nginx reverse proxy. Could you please point me to an example of how to properly proxy Selenoid web sockets?

I'm getting: "Error during WebSocket handshake: Unexpected response code: 403"
![2020-03-10_17h42_17](https://user-images.githubusercontent.com/17275156/76336766-c2ecd800-62f6-11ea-801e-02b3bf5eab1b.png)

I have tried dozens of Nginx configurations and I'm not able to solve it.

Many thanks in advance.
