### ISSUE TITLE
Unable to see updates in selenoid-ui on windows via Edge browser

### ISSUE THREAD

**Issue by andrew-sumner** [aerokube/selenoid-ui#147]
I've tried docker and binaries:

C:\Work\selenium>selenoid.exe --version
Git Revision: 1.9.1
UTC Build Time: 2019-03-14_10:19:10AM

C:\Work\selenium>selenoid.exe
2019/05/13 12:28:40 [-] [INIT] [Loading configuration files...]
2019/05/13 12:28:40 [-] [INIT] [Loaded configuration from config/browsers.json]
2019/05/13 12:28:40 [-] [INIT] [Video Dir: C:\Work\selenium\video]
2019/05/13 12:28:40 [-] [INIT] [Your Docker API version is 1.39]
2019/05/13 12:28:40 [-] [INIT] [Timezone: Local]
2019/05/13 12:28:40 [-] [INIT] [Listening on :4444]

C:\Work\selenium>selenoid-ui --version
Git Revision: 1.6.6
UTC Build Time: 2019-03-26_02:13:20AM

C:\Work\selenium>selenoid-ui --selenoid-uri http://localhost:4444
2019/05/13 12:29:00 Listening on :8080

http://localhost:4444/status returns {"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"73.0":{},"74.0":{}},"firefox":{"65.0":{},"66.0":{}},"opera":{"58.0":{},"60.0":{}}}}

http://localhost:8080/#/capabilities/ opens UI but SSE showing in red and no browsers listed in dropdown. Also cannot see any sessions.  

Are able to run tests against Selenoid to I know that is working.

**Comment by vania-pooh** [comment]
@andrew-sumner there should be an error message in Selenoid UI logs then.

**Comment by andrew-sumner** [comment]
I assume the only logs are what appears on the console when running the binary?  That only states that it's listening.

**Comment by vania-pooh** [comment]
@andrew-sumner couldn't it be a firewall-related issue?

**Comment by andrew-sumner** [comment]
I don't think it's firewall related as everything is running locally.  I've created a test using C# / RemoteWebDriver / Chrome using selenoid and that works fine, takes videos and everything. Selenoid-UI doesn't register any running tests, nor show any browsers under capabilities.

Are there any log files for selenoid-ui output anywhere other than the console? This only shows:
```
C:\Work\selenium>selenoid-ui --selenoid-uri http://localhost:4445
2019/05/14 10:58:02 Listening on :8080
```

**Comment by andrew-sumner** [comment]
Ok, just got weirder... realised that I can tack "status" to the selenoid-ui url (eg `http://localhost:8080/status`) and that shows the full list of browsers and sessions running in selenoid. So why wouldn't this show in the UI?!

**Comment by andrew-sumner** [comment]
Ah, I'm using Edge, switched over to Chrome and all is good.

Perhaps there could be a warning somewhere that Edge isn't supported?

**Comment by vania-pooh** [comment]
@andrew-sumner VNC only works for browsers in containers. If you pack Edge to Docker image - then it will also work.

**Comment by lanwen** [comment]
I think that's about the browser to access selenoid-ui. Actually, it pretended to work with edge.

@andrew-sumner can you show the developer console errors when you access via edge? Should be something there

**Comment by andrew-sumner** [comment]
@lanwen Will do as soon as I get selenoid up and running again - doing a clean install on a windows server and having some fun even getting docker installed...
