### ISSUE TITLE
Restrict access

### ISSUE THREAD

**Issue by jsa34** [aerokube/selenoid-ui#151]
Hello,
I was wondering if there were any way to restrict access to view the selenoid-ui pages?
Any suggestions gratefully appreciated!
J

**Comment by vania-pooh** [comment]
@jsa34 how about https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/ ?

**Comment by istvandesign** [comment]
Can you add nginx-plus and expose /etc/nginx/conf.d/frontend.conf as a config for the docker image ? 
I think that would be enough for most people, even for enterprise users. (one can just use openID)

**Comment by aprilahijriyan** [comment]
Has this feature been added?

**Comment by vania-pooh** [comment]
@aprilahijriyan yes, in release 1.10.2. See http://aerokube.com/selenoid-ui/latest/#_restricting_access
