### ISSUE TITLE
Problem in chrome in new tab for video when there is a lot of them

### ISSUE THREAD

**Issue by ShinKaiRyuu** [aerokube/selenoid-ui#157]
Selenoid-UI v1.7.0
Tab with videos hangs up in Chrome when there is a lot of them: 
When count of videos is too big - tab just hangs in Chrome on loading all video players.
Firefox loads same page just fine ( as it could)  ( 390 videos)
![image](https://user-images.githubusercontent.com/2714369/60961213-4d1e1000-a314-11e9-992f-76039230b3b0.png)

**Comment by vania-pooh** [comment]
@ShinKaiRyuu could be because currently video is using `preload = auto` property.
```
<video controls preload="auto">
```
@eacevedo79 any ideas how to improve this?

**Comment by eacevedo79** [comment]
i'll look into it, i'm thinking either setting `preload="none"` or using something like https://github.com/scrollreveal/scrollreveal may help.
i'll update here with my findings.

**Comment by ShinKaiRyuu** [comment]
Found a new problem after updating main server to new selenoid and selenoid-ui versions. We have 2000+ videos and this cause weird communicating problem with getting status and using vnc sessions of active right now tests 
![image](https://user-images.githubusercontent.com/2714369/61035902-ad728780-a3d0-11e9-8a7f-429a1d5275d2.png)

**Comment by vania-pooh** [comment]
@ShinKaiRyuu let's first fix this one and see whether it helps.
