### ISSUE TITLE
The problem of displaying dashboard and video tab elements

### ISSUE THREAD

**Issue by f0rzer** [aerokube/selenoid-ui#184]
In version of selenoid-ui 1.8.1, length of the test name affects length of the ui-element

checked in:
firefox 68.0.1
chrome 76.0.3809.87

in version 1.8.0 there was no problem

**Comment by lanwen** [comment]
@f0rzer Hello, can you send a screenshot? I didn't get what the ui-element you are talking about?

**Comment by f0rzer** [comment]
![111111112](https://user-images.githubusercontent.com/24559628/63141829-6734c780-c011-11e9-9e9b-58565334d397.jpg)

**Comment by f0rzer** [comment]
![1234567](https://user-images.githubusercontent.com/24559628/63141999-170a3500-c012-11e9-89e2-b0ca7451feec.png)

**Comment by lanwen** [comment]
Main screen was changed to be more like table, video will be reworked as well

**Comment by f0rzer** [comment]
@lanwen thank!

**Comment by lanwen** [comment]
#255 and #262 should address an issue (you can check that on `latest` docker tag). Feel free to open if not
