### ISSUE TITLE
Video tab in selenoid-ui eats all my RAM 

### ISSUE THREAD

**Issue by ghost** [aerokube/selenoid-ui#185]
I've tried latest `selenoid` image (1.9.2 version) and `selenoid-ui` (1.8.1 iamge tag) and oversaw new video tab. Looks cool but if you have many videos (lets suppose 30000) Chrome (maybe not just it) eats all RAM memory during rendering of all videos. Can I turn off it somehow?

**Comment by ybychenok** [comment]
Ok. Seems for now will be better for me to use latest ui and `1.9.1` selenoid image.

**Comment by vania-pooh** [comment]
@ybychenok we already applied a fix in 1.8.1 that automatically disables view preview in `<video>` tag when number of videos is greater than 100. Probably this needs more investigation.

**Comment by ybychenok** [comment]
@vania-pooh  is it possible to add some env.variable to disable video tab? Seems limitation described by you isn't working. Thanks.

**Comment by vania-pooh** [comment]
@ybychenok I don't know about such env variables. How many videos do you have?
@lanwen any ideas for improvements?

**Comment by lanwen** [comment]
Just don't use it then, why disable? :) I would try to implement lazy loading, so that not more than visible on screen videos loaded.

**Comment by ybychenok** [comment]
On prod - 46653
On dev - 998

> Just don't use it then, why disable

It's hard to explain for 150 people team to not use that tab. I am sure if I ask them not to do that - they definitely try that.

> I would try to implement lazy loading, so that not more than visible on screen videos loaded.

Maybe some pagination is fine too. I am OK with all such solutions.
