### ISSUE TITLE
Prevent accidental deletion by delete button

### ISSUE THREAD

**Issue by aandryashin** [aerokube/selenoid-ui#199]
To prevent accidental autotest session deletion.

**Comment by lanwen** [comment]
what if it gets stuck and we want to kill it anyway? We also were asked about the deletion button for the regular sessions as well. I think better to just confirm in some way the deletion, but not hide that

**Comment by aandryashin** [comment]
Stuck sessions can be removed by system administrator using curl. Ability
to kill any session by anybody is danger, that is why vnc by default in
read only mode.

пт, 16 авг. 2019 г., 3:12 Kirill Merkushev <notifications@github.com>:

**Comment by lanwen** [comment]
admins are using ui as well, we can't support both administrative and qa cases without roles introduction, so we just have to make sure no accidental deletions with the same as vnc approach - asking with additional info provided. Also we can't fully distinguish manual sessions from regular ones

**Comment by tymfear** [comment]
Duplicates #160

**Comment by lanwen** [comment]
related, but not duplicates

**Comment by tymfear** [comment]
@lanwen yeah, you're right. Posted to not to loose it.
