### ISSUE TITLE
Constant url for getting VNC of first session

### ISSUE THREAD

**Issue by pavelsr** [aerokube/selenoid-ui#203]
I want to debug my script with VNC window opened.

Selenoid UI has route like

http://localhost:8080/#/sessions/2ae94311cf5479d941f10db17da19df9

for viewing session via VNC

But for that I need to know session id. 

Do you have route like 

http://localhost:8080/#/sessions/first/vnc

which will constantly open VNC window of first runned session ?

**Comment by vania-pooh** [comment]
@pavelsr no, this is currently missing. What's the use case?

**Comment by pavelsr** [comment]
The use case is visual control of Selenoid script, to define what exactly stucked it.

E.g. I have a case when after submitting registration button there is alert with error.

**Comment by vania-pooh** [comment]
@pavelsr how about just using Selenoid UI?

**Comment by vania-pooh** [comment]
@pavelsr how about using `name` capability in test and then clicking on respective labeled session button?

**Comment by pavelsr** [comment]
I know about [this capability](https://github.com/aerokube/selenoid/blob/master/docs/special-capabilities.adoc#custom-test-name-name).

But I can not find how to get session by name in selenoid-ui

E.g. I started driver with

```
use Selenium::Remote::Driver;
my $driver = Selenium::Remote::Driver->new( 
    browser_name => 'chrome', 
    extra_capabilities => { enableVNC => \1,  },
    sessionTimeout => '10s',
    name => 'xxx'
);
```

and then went to http://localhost:8080/#/sessions/xxx

But screen was empty. What is the correct url ?

**Comment by vania-pooh** [comment]
@pavelsr Selenium is operating using so-called session identifiers (usually the look like UUIDs, e.g. `0ee0b48b-e29b-6749-b4f1-2277b8f8d6c5`). By default when session is created such identifier is accessible via `driver.session_id` property or method with similar name (I think in Perl it should be `$driver->session_id`). Just substitute this variable instead of `xxx` and it should work.

**Comment by pavelsr** [comment]
So no way to address session by its name specified in extra_capabilities ?

**Comment by vania-pooh** [comment]
@pavelsr no, name is not unique.

**Comment by pavelsr** [comment]
Ok, thank you.

FYI I can get the direct url using Perl driver like this

```perl
my $driver = Selenium::Remote::Driver->new(%params);
$driver->get('https://example.com');
system( "xdg-open", "http://localhost:8080/#/sessions/" . $driver->session_id );
```
