### ISSUE TITLE
Enable docker healthcheck

### ISSUE THREAD

**Issue by giggio** [aerokube/selenoid-ui#208]
I haven't found a way to do a healthcheck, as I can't install `curl` on the image.
What would be the proper way to do that?

**Comment by vania-pooh** [comment]
@giggio there should be a `GET /ping` API.

**Comment by giggio** [comment]
Ok, but we can't GET if there is no curl.

This is how I managed to do it:

````go
package main

import (
  "net/http"
  "os"
)

func main() {
  _, err := http.Get("http://localhost/ping")
  if err != nil {
    os.Exit(1)
  }
}
````

And on the Dockerfile:

````Dockerfile
FROM golang:1.13 as buildImage
WORKDIR /go/src/lambda3/healthcheck
COPY healthcheck.go .
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o health-check "lambda3/healthcheck"

FROM aerokube/selenoid-ui:1.8.1
COPY --from=buildImage /go/src/lambda3/healthcheck/health-check ./healthcheck
HEALTHCHECK --interval=1s --timeout=1s --start-period=2s --retries=3 CMD [ "/healthcheck" ]
````

It has some hardcoded values on it, but you get the idea.

**Comment by vania-pooh** [comment]
@giggio ok, thank you for the snippet. But what's the use case?

**Comment by giggio** [comment]
To know the health status of Solenoid UI.

https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by vania-pooh** [comment]
@giggio let's add it to docs then.

**Comment by giggio** [comment]
Ideally you would add something like that to the selenoid-ui docker image. Health checks are important, it should be in the box, IMO.

**Comment by giggio** [comment]
Any idea of when the next release is expected?

**Comment by lanwen** [comment]
@giggio Hey, thanks for pinging. On this weekend!
