### ISSUE TITLE
Enable Clipboard Sharing in VNC Session

### ISSUE THREAD

**Issue by rorylshanks** [aerokube/selenoid-ui#215]
To make the manual session feature better, having some way of sharing clipboards would be awesome.

Potentially a textbox under the VNC window that allows you to send and receive clipboard data from the noVNC RFB?

**Comment by vania-pooh** [comment]
Related to https://github.com/novnc/noVNC/issues/509.

**Comment by Tyson1986** [comment]
@vania-pooh looks like the related noVNC issue is closed. Could you take a look? Maybe it will not take much time to fix it by updating the version.

**Comment by vania-pooh** [comment]
@Tyson1986 so far as I can see it was just closed as `won't fix`.
