### ISSUE TITLE
Make "close-session" button optional by a flag

### ISSUE THREAD

**Issue by lirik44** [aerokube/selenoid-ui#252]
"Close session" button was disappeared in last release, it was very useful for some users, Maybe make it optional by key?

**Comment by lanwen** [comment]
You can already do that if you add  `labels` `->` `manual: true` capability 

```
 labels: { manual: "true" },
```
(in the `desiredCapabilities`)

will add that into docs

you can find how the interface is launching a session here: https://github.com/aerokube/selenoid-ui/blob/master/ui/src/containers/Capabilities/index.js#L172-L198

will that solve an issue?

**Comment by lanwen** [comment]
Feel free to reopen if you think that should be improved additionally
