### ISSUE TITLE
Support multiple selenoid instances

### ISSUE THREAD

**Issue by mdolinin** [aerokube/selenoid-ui#28]
Feature request
Provide ability to connect to multiple selenoid-uri.
For big clusters of selenoids, it will be great to have ability to see stats from one UI.

**Comment by lanwen** [comment]
Please consider to use Telegraf: http://aerokube.com/selenoid/latest/#_sending_statistics_to_external_systems

Or try to use swarm with selenoid.

Selenoid-ui mostly the debug purposes for small installation or for exact instance monitoring.

Maybe this point will be reworked, but now to aggregate stats for multiple instances, please use standalone stats backends.
