### ISSUE TITLE
Feature or bug

### ISSUE THREAD

**Issue by emilorol** [aerokube/selenoid-ui#294]
I noticed that on the latest Selenoid UI the older hash has been replace to the first number:

![trim-down](https://user-images.githubusercontent.com/9518604/72937604-6ed26800-3d37-11ea-805e-925ab0f54eb5.png)

Is this ok?

**Comment by vania-pooh** [comment]
@emilorol in fact it was not. It is still showing first 8 chars of session ID. However in Moon session ID differs from what you had in Selenoid.

**Comment by emilorol** [comment]
Perfect. Thank you.
