### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by giggio** [aerokube/selenoid-ui#295]
I've noticed that Selenoid UI is using between 20% and 30% of CPU, even though nobody is connected to it and there are no sessions running. Would it be possible to get this closer to no CPU usage when nobody is using it?

**Comment by giggio** [comment]
Ok, I noticed that this was due to a health check ocurring every second. I'm using 60 seconds now and the high CPU usage is gone.

This might also occur after #269 as well. I was testing the `/ping` endpoint, so I'm not sure if this will happen on your new implementation.

**Comment by giggio** [comment]
Ok, now that 1.9.2 was released, I can confirm this is an issue. I had to manually add another health check with a longer interval.

**Comment by lanwen** [comment]
Hey, @giggio how did you noticed that btw?

anyway would reduce the rate, definitely its not needed to be checked every sec

**Comment by giggio** [comment]
We noticed that our Docker Server was showing CPU usage under no load, and investigated.
