### ISSUE TITLE
selenoid 1.9.2 shows unhealthy

### ISSUE THREAD

**Issue by jsa34** [aerokube/selenoid-ui#299]
After updating from 1.9.1 to 1.9.2, selenoid shows unhealthy.
***UPDATE: Just noticed 1.9.2 added the health check, so could have been an issue with 1.9.1 and previous***

Starting selenoid or using ggr-ui endpoints both result in the same behaviour.

Command used: ./cm selenoid-ui start --args "--selenoid-uri=http://hostname:8888"

Docker logs for container:
Feb  4 12:13:29 hostname dockerd: time="2020-02-04T12:13:29.536901982Z" level=warning msg="Health check for container b941eced687282f83e24b6a94512e9843d9be433402c4493be45fe3f68a9a52b error: context deadline exceeded"

**Comment by lanwen** [comment]
please check #277 and tell if more details would pop up

**Comment by lanwen** [comment]
Assume solved

**Comment by jsa34** [comment]
Apologies - I completely forgot to reply as I just downgraded to v 1.9.1 to avoid the healthy/unhealthy status issues.  This is still an issue no matter how I seem to start the containers

**Comment by lanwen** [comment]
@jsa34 did you do same steps to get the reason as described in #277?
