### ISSUE TITLE
Selenoid ui not loaded in mac os browser

### ISSUE THREAD

**Issue by sasha943** [aerokube/selenoid-ui#313]
**Mac os version:** 10.14.6
**Docker version:** 19.03.6, build 369ce74
**Docker-machine version** version 0.16.2, build bd45ab1

For setup environment I followed next instructions: [link](https://medium.com/@yutafujii_59175/a-complete-one-by-one-guide-to-install-docker-on-your-mac-os-using-homebrew-e818eb4cfc3)

Start selenoid-ui with next command:
`docker run -d --name selenoid-ui --link selenoid -p 8080:8080 aerokube/selenoid-ui`

After executing command:
`docker ps -a` have a result:

> eae753d3fb00        aerokube/selenoid-ui               "/selenoid-ui --sele…"   3 days ago          Up 1 second (health: starting)   0.0.0.0:8080->8080/tcp   selenoid-ui
> e0028458cbfc        aerokube/selenoid:latest-release   "/usr/bin/selenoid -…"   3 days ago          Up 5 seconds                     0.0.0.0:4445->4444/tcp   selenoid

After executing command:
`docker log -f selenoid-ui`:
**Result:**

> 2020/02/28 12:34:51 [INIT] [Listening on :8080]
2020/02/28 13:43:23 [INIT] [Listening on :8080]
2020/03/03 11:41:38 [INIT] [Listening on :8080]

But when open browser and type link: `http://localhost:8080` **UI not loaded**

Please advice...

**Comment by vania-pooh** [comment]
@sasha943 do you have stuff like "Connection error" or some Javascript errors?

**Comment by sasha943** [comment]
@vania-pooh no js errors, page not loaded at all

**Comment by vania-pooh** [comment]
@sasha943 at least according to docs should be:
```
$ docker run -d --name selenoid-ui --link selenoid -p 8080:8080 aerokube/selenoid-ui --selenoid-uri http://selenoid:4444
```

**Comment by sasha943** [comment]
@vania-pooh yes, you are right. Restart selenoid-ui with new command and all errors from logs disappear. In caps displayed images from browser.json

**Comment by vania-pooh** [comment]
@sasha943 so it works?

**Comment by sasha943** [comment]
@vania-pooh selenoid-ui yes, now I have problem with connection to selenoid from tests (it§s other problem)
