### ISSUE TITLE
Selenoid-UI VNC/logs disconnected in linux environment (works in MacOS)

### ISSUE THREAD

**Issue by Minion0313** [aerokube/selenoid-ui#314]
![image](https://user-images.githubusercontent.com/61898787/76138121-6ea1d980-6012-11ea-88ff-abd626d93c79.png)
Hi i am using selenoid and selenoid ui in docker for running selenoium tests
everything works perfectly in Mac os... i am able to see my test executions on the selenoid UI
But the same set up does not work on the linux (My office laptop)
dont know what is the issue 
getting vnc disconnected the set up is all same is mac and linux except the difference is that mac is personal system and linux is my office laptop 
Please help me resolve the issue
thanks in advance
@vania-pooh

**Comment by vania-pooh** [comment]
@Minion0313 take a look at browser images you are using. They should have `vnc` in image name.

**Comment by Minion0313** [comment]
@vania-pooh Hi thank you for the response
Initially when i installed it had vnc chrome browser
but when i deleted the cm(configuration manager) and re-installed again i am getting only these below images 
![image](https://user-images.githubusercontent.com/61898787/76156580-60af8f80-60ca-11ea-8e0b-d131a5f053ed.png)
Even though VNC image is not there, i am able to see my tests running on selenoid ui (this is in my personal mac)
But i dont see them running in my Linux my office laptop ( getting vnc disconncted)

and one curious question why i am not getting all the omages which i used to previously the along with vnc now ?

thanks in advance
Response is much appreciated

**Comment by Minion0313** [comment]
> @Minion0313 take a look at browser images you are using. They should have `vnc` in image name. If that does not help - please take a look at browser console images.

How can i look at the browser console images

**Comment by Minion0313** [comment]
@vania-pooh I updated my browers.json file and reloaded selenoid
still i am getting the same issue

![image](https://user-images.githubusercontent.com/61898787/76156729-876ec580-60cc-11ea-8ddf-150b14982e34.png)

here is my browsers.json file (I added vnc chrome)
![image](https://user-images.githubusercontent.com/61898787/76156736-acfbcf00-60cc-11ea-9442-3c76bba96f43.png)

This is only happening in my office laptop
It works perfectly well in my personal laptop

**Comment by vania-pooh** [comment]
@Minion0313 console messages are usually available in browser developer toolbar. There is a section called Console there. Currently both `vnc` and non-vnc images contain VNC server. Previously that was not the case.
<img width="767" alt="Screen Shot 2020-03-08 at 11 02 29" src="https://user-images.githubusercontent.com/829320/76158940-57efa580-612c-11ea-9b76-3ae3efe45a87.png">

**Comment by lanwen** [comment]
@Minion0313 It would be helpful if you could provide us selenoid and selenoid-ui logs when this disconnect happens.

**Comment by Minion0313** [comment]
@lanwen @vania-pooh 
hi thank you for the response
i was not able to resolve the issue yet and here are the logs when i am running the tests, this is what it is showing on the selenoid-ui
![image](https://user-images.githubusercontent.com/61898787/76312532-aaa29c00-62a9-11ea-9ce0-b0430a5838ec.png)
Please let me know who could i resolve this issue

**Comment by lanwen** [comment]
@Minion0313 thanks for sharing! I would ask you next time just copy the output and put it here as a text :) and don't forget to edit internal hosts and replace it with something like "our.company.host.com" (literally), so no internal infrastructure is exposed.

As I can see, selenoid is returning `Forbidden` status code - do you have any kind of auth before selenoid?

**Comment by Minion0313** [comment]
@lanwen sure lanwen i will do that , from next time
i did not do anything in particular
when i installed docker i did set up proxy thing in the config file
and also when i pull the selenoid ui image with cm command it wouldn't link properly so i had to remove the image and pull it manually and link it using the below command

docker run -d --name selenoid-ui --link selenoid -p 8080:8080 aerokube/selenoid-ui --selenoid-uri http://myhostname:4444
then only it would be properly connected

**Comment by lanwen** [comment]
@Minion0313 you then trying to reach wrong host - for the selenoid-ui `selenoid-uri` should be  `http://selenoid:4444` can you try that?

What's the issue with cm? Can I kindly ask you to report that to appropriate repo?

**Comment by Minion0313** [comment]
> @Minion0313 you then trying to reach wrong host - for the selenoid-ui `selenoid-uri` should be `http://selenoid:4444` can you try that?
> 
> What's the issue with cm? Can I kindly ask you to report that to appropriate repo?

do u mean something linke thsi

docker run -d --name selenoid-ui --link selenoid -p 8080:8080 aerokube/selenoid-ui http://selenoid:4444  http://myhostname:4444

**Comment by Minion0313** [comment]
@lanwen so the issue with cm i am facing is, when i do 
./cm start selenoid-ui 
it is no automatically linking the selenoid to selenoid ui port
so i had to giv ethat additional command

**Comment by lanwen** [comment]
Not exactly - selenoid-ui doesn't care about your host. 
So as stated in docs it should be 

```
docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui --link selenoid --selenoid-uri http://selenoid:4444
```

**Comment by Minion0313** [comment]
> Not exactly - selenoid-ui doesn't care about your host.
> So as stated in docs it should be
> 
> ```
> docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui --link selenoid --selenoid-uri http://selenoid:4444
> ```
sorry for asking it again in this url "http://selenoid:4444" selenoid is the host where i am pointing to i mean is it like
ex if selenoid url is http://myhostname:4444
in the url forthe command it should be myhostname or selenoid?
because this is the url i am using to access selenoid http://myhostname:4444 or any status http://myhostname:4444/status or i am able to see when my tests run the session is created in the selenoid ui in http://myhostname:8080(with vnc disconnected issue)

**Comment by Minion0313** [comment]
I am not able to link it using the above command , i am anot able to access selenoid ui

**Comment by lanwen** [comment]
Just copy as is. `selenoid` is the host name for the container, not for you.

**Comment by lanwen** [comment]
sorry, my bad 
```
docker run -d --name selenoid-ui -p 8080:8080 --link selenoid aerokube/selenoid-ui --selenoid-uri http://selenoid:4444
```

misplaced `link` arg

**Comment by Minion0313** [comment]
> Just copy as is. `selenoid` is the host name for the container, not for you.

thank u for the reply, so what will be the url for accessing selenoid ui?
will that be the same i.e http://myhostname:8080?
correct me if i am wrong

**Comment by Minion0313** [comment]
@lanwen thank u for ur patience

**Comment by Minion0313** [comment]
@lanwen corrected and gave the above command
![image](https://user-images.githubusercontent.com/61898787/76317151-125ce500-62b2-11ea-8661-496d41a69123.png)
 this is what it shows

**Comment by lanwen** [comment]
@Minion0313 please always provide all available logs.
Url for your selenoid-ui access wouldn't change.

**Comment by Minion0313** [comment]
@lanwen sorry this is what it shows
2020/03/10 13:30:56 [INIT] [Listening on :8080]
2020/03/10 13:31:22 Client added. 1 registered clients
2020/03/10 13:31:22 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:31:26 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:31:31 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:31:36 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:31:41 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:31:46 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:31:51 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:31:56 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:01 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:06 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:11 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:16 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:21 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:26 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:31 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:36 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:41 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:46 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:51 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:32:56 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:33:01 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:33:06 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:33:11 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:33:16 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:33:21 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:33:26 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:33:31 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 13:33:36 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]

**Comment by lanwen** [comment]
Ok, lets get back to the beginning.
Please kill and remove all containers for selenoid and selenoid-ui
then run cm commands as stated in the manual
then if it still shows this picture,  provide all the outputs of the commands, docker ls, and docker inspect for the selenoid-ui

**Comment by Minion0313** [comment]
@lanwen before using the command which u have given  i was using this command 

docker run -d --name selenoid-ui -p 8080:8080 --link selenoid aerokube/selenoid-ui --selenoid-uri http://hostname:4444

i was atleast able to see the session created 
now i am not able to see any session also

**Comment by Minion0313** [comment]
> Ok, lets get back to the beginning.
> Please kill and remove all containers for selenoid and selenoid-ui
> then run cm commands as stated in the manual
> then if it still shows this picture, provide all the outputs of the commands, docker ls, and docker inspect for the selenoid-ui

ok i will do that

**Comment by Minion0313** [comment]
Still facing the same issue @lanwen 
here are the steps followed from manual and also the output 
befor i started deleted all the images and containers
[root@myhostname a627853]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

[root@myhostname a627853]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

[root@myhostname selenoid]# curl -s https://aerokube.com/cm/bash | bash

[root@myhostname selenoid]# curl -s https://aerokube.com/cm/bash | bash \
> && ./cm selenoid start --vnc

 █████╗ ███████╗██████╗  ██████╗ ██╗  ██╗██╗   ██╗██████╗ ███████╗     ██████╗███╗   ███╗
██╔══██╗██╔════╝██╔══██╗██╔═══██╗██║ ██╔╝██║   ██║██╔══██╗██╔════╝    ██╔════╝████╗ ████║
███████║█████╗  ██████╔╝██║   ██║█████╔╝ ██║   ██║██████╔╝█████╗      ██║     ██╔████╔██║
██╔══██║██╔══╝  ██╔══██╗██║   ██║██╔═██╗ ██║   ██║██╔══██╗██╔══╝      ██║     ██║╚██╔╝██║
██║  ██║███████╗██║  ██║╚██████╔╝██║  ██╗╚██████╔╝██████╔╝███████╗    ╚██████╗██║ ╚═╝ ██║
╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝     ╚═════╝╚═╝     ╚═╝

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   604  100   604    0     0   3061      0 --:--:-- --:--:-- --:--:--  3065
100 12.5M  100 12.5M    0     0  2805k      0  0:00:04  0:00:04 --:--:-- 3032k

SUCCESSFULLY DOWNLOADED!

Git Revision: 1.7.1
UTC Build Time: 2019-10-08_05:28:51PM

Now you can run Selenoid with cm:
    ./cm selenoid start --vnc

To get instant help just type:
    ./cm --help

> Using Docker
- Your Docker API version is 1.40
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://registry.hub.docker.com/v2/
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.10.0
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid


[root@myhostname selenoid]# ./cm selenoid update
> Using Docker
- Your Docker API version is 1.40
> Downloading Selenoid...
- Fetching tags for image aerokube/selenoid
registry.ping url=https://registry.hub.docker.com/v2/
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid/tags/list repository=aerokube/selenoid
- Pulling image aerokube/selenoid:1.10.0
> Configuring Selenoid...
> Processing browser "firefox"...
- Fetching tags for image selenoid/firefox
registry.tags url=https://registry.hub.docker.com/v2/selenoid/firefox/tags/list repository=selenoid/firefox
- Pulling image selenoid/firefox:73.0
- Pulling image selenoid/firefox:72.0
> Processing browser "chrome"...
- Fetching tags for image selenoid/chrome
registry.tags url=https://registry.hub.docker.com/v2/selenoid/chrome/tags/list repository=selenoid/chrome
- Pulling image selenoid/chrome:80.0
- Pulling image selenoid/chrome:79.0
> Processing browser "opera"...
- Fetching tags for image selenoid/opera
registry.tags url=https://registry.hub.docker.com/v2/selenoid/opera/tags/list repository=selenoid/opera
- Pulling image selenoid/opera:67.0
- Pulling image selenoid/opera:66.0
> Pulling video recorder image...
- Pulling image selenoid/video-recorder:latest-release
> Configuration saved to /root/.aerokube/selenoid/browsers.json
> Stopping previous Selenoid instance...
> Stopping Selenoid...
> Successfully stopped Selenoid
> Starting Selenoid...
> Successfully started Selenoid

[root@myhostname selenoid]# ./cm selenoid-ui start
> Using Docker
- Your Docker API version is 1.40
> Downloading Selenoid UI...
- Fetching tags for image aerokube/selenoid-ui
registry.ping url=https://registry.hub.docker.com/v2/
registry.tags url=https://registry.hub.docker.com/v2/aerokube/selenoid-ui/tags/list repository=aerokube/selenoid-ui
- Pulling image aerokube/selenoid-ui:1.9.2
> Starting Selenoid UI...
> Successfully started Selenoid UI
[root@myhostname selenoid]# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS                    PORTS                    NAMES
0f0d4aab68c5        aerokube/selenoid-ui:1.9.2   "/selenoid-ui --sele…"   22 seconds ago       Up 21 seconds (healthy)   0.0.0.0:8080->8080/tcp   selenoid-ui
9f424bf31c07        aerokube/selenoid:1.10.0     "/usr/bin/selenoid -…"   About a minute ago   Up About a minute         0.0.0.0:4444->4444/tcp   selenoid

Since its is not linking automatically i have deleted the image and given thenext command 
[root@myhostname selenoid]# docker run -d --name selenoid-ui -p 8080:8080 --link selenoid aerokube/selenoid-ui --selenoid-uri http://selenoid:4444
7e864ca62c27b41d20be8f7e8d31e6a2c11b71378814bf2504cd96352ce7652b

**Comment by lanwen** [comment]
@Minion0313 hey, thx a lot, can you elaborate on how do you know its not linking automatically?

Selenoid-ui says its `Up 21 seconds (healthy)` which exactly means everything was linked fine

**Comment by Minion0313** [comment]
> @Minion0313 hey, thx a lot, can you elaborate on how do you know its not linking automatically?
> 
> Selenoid-ui says its `Up 21 seconds (healthy)` which exactly means everything was linked fine

Hi on the selenoid-UI It was showing not connected

**Comment by Minion0313** [comment]
> > @Minion0313 hey, thx a lot, can you elaborate on how do you know its not linking automatically?
> > Selenoid-ui says its `Up 21 seconds (healthy)` which exactly means everything was linked fine
> 
> Hi on the selenoid-UI It was showing not connected

I mean on the actual UI it was not Connected like showing unknown error

**Comment by lanwen** [comment]
@Minion0313 okay, now I need docker logs for selenoid and selenoid-ui, as well as curl results for the /status endpoint of selenoid (right after you've done with cm)

**Comment by Minion0313** [comment]
Hi @lanwen  thank you for the response
here is the curl status and docker logs for selenoid and selenoid-ui

[root@myhostname a627853]# curl http://myhostname.fmr.com:4444/status
{"total":5,"used":0,"queued":0,"pending":0,"browsers":{"chrome":{"79.0":{},"80.0":{}},"firefox":{"72.0":{},"73.0":{}},"opera":{"66.0":{},"67.0":{}}}}


[root@myhostname a627853]# docker logs selenoid -f
2020/03/10 13:55:11 [-] [INIT] [Loading configuration files...]
2020/03/10 13:55:11 [-] [INIT] [Loaded configuration from /etc/selenoid/browsers.json]
2020/03/10 13:55:11 [-] [INIT] [Video Dir: /opt/selenoid/video]
2020/03/10 13:55:11 [-] [INIT] [Logs Dir: /opt/selenoid/logs]
2020/03/10 13:55:11 [-] [INIT] [Using Docker API version: 1.40]
2020/03/10 13:55:11 [-] [INIT] [Timezone: UTC]
2020/03/10 13:55:11 [-] [INIT] [Listening on :4444]


[root@myhostname a627853]# docker logs --tail 15 selenoid-ui
2020/03/10 16:51:48 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:51:53 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:51:58 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:03 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:08 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:13 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:18 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:23 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:28 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:33 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:38 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:43 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:48 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:53 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]
2020/03/10 16:52:58 [ERROR] [Can't get status: invalid character '<' looking for beginning of value]

**Comment by Minion0313** [comment]
@lanwen dev console status

![image](https://user-images.githubusercontent.com/61898787/76338747-835ec580-62cf-11ea-8e5e-e8c7125aa4c4.png)

**Comment by lanwen** [comment]
@Minion0313 thank you a lot, wondering why selenoid-ui gets html instead of json as a response for status.

You greatly could help to identify the issue if would launch ubuntu container same way linked to a selenoid and launch curl for the `http://selenoid/status` (basically repeat what selenoid-ui) is doing. 

I would try to reproduce that on my side in a few days.

Thank's a lot, appreciate your help in investigations

**Comment by Minion0313** [comment]
@lanwen thank u for the help how could i fix the actual issue now

**Comment by lanwen** [comment]
@Minion0313 that still not clear for me, that's why I need further assistance from your side
