### ISSUE TITLE
Show available custom capabilities

### ISSUE THREAD

**Issue by lanwen** [aerokube/selenoid-ui#33]
As multiselect with influence to example.
Maybe provide special node in status handle for available custom capabilities

Show selector with "screenResolution", "enableVNC" and add to example if checked. Maybe add some description which will look like comment

**Comment by vania-pooh** [comment]
Fixed in https://github.com/aerokube/selenoid-ui/pull/32.

**Comment by piotrkochan** [comment]
https://github.com/aerokube/selenoid-ui/pull/284

**Comment by ShinKaiRyuu** [comment]
Custom usecase for capability like environment : We have multiple application host - so i create a session with custom label like environments with value for example TeamCity ( used lable just for example like "manual")
![image](https://user-images.githubusercontent.com/2714369/88778859-b4159d80-d191-11ea-9a99-d5c37dac33fa.png) , please add ability to view this capability right in grid with active sessions

**Comment by lanwen** [comment]
This could be added here iterating over labels
https://github.com/aerokube/selenoid-ui/blob/master/ui/src/components/Sessions/index.js#L93

![image](https://user-images.githubusercontent.com/1964214/88788199-49666100-d195-11ea-85bb-733c68e98c49.png)
that would look something like this
![image](https://user-images.githubusercontent.com/1964214/88788237-58e5aa00-d195-11ea-9156-b061b6142bbf.png)

needs to be tested with different labels length as well as their number. I would propose something like `key:value` as the content of the badge, but maybe just value could be fine as well - feel free to try different ways
