### ISSUE TITLE
video view update

### ISSUE THREAD

**Issue by eacevedo79** [aerokube/selenoid-ui#344]
Hi, this is more of a feature request that i can contribute if agreed upon.
the video view is used extensibly where i work and we would like it to be a bit more feature rich.
this are a few features we were thinking of:

* add creation date to the ui so the view can sorted.
* maybe have 2 modes in view thumbnails/player and table.
* pagination, show only X videos per page.

i understand some or all of this will require changes on selenoid as well, i'm open to implementing that too.

Thanks.

**Comment by espguitarist33** [comment]
+1 these features would be great.  The ability to search by test name would be extremely helpful as well.  The UUID displayed is not helpful

**Comment by vania-pooh** [comment]
@lanwen is this feature complicated to implement?

**Comment by lanwen** [comment]
right now i have only video ids, so for everything additional I need new api. Pagination is not super hard to implement. Its even can be done purely on the web

**Comment by pranav165** [comment]
If possible can we add feature to show all live sessions running .  Some thing like this below , i would like to monitor 5 sessions together , right now i need to open 5 tabs and switch back and forth

![image](https://user-images.githubusercontent.com/26303706/99778627-f0527c80-2b39-11eb-8dc0-fcb1c4c2a0b4.png)
