### ISSUE TITLE
Unable to delete non-manual sessions in 1.10

### ISSUE THREAD

**Issue by b71729** [aerokube/selenoid-ui#353]
Using the web UI it appears that the button to delete a session is, as of #213, restricted to only those sessions that are labelled as `manual`.

This logic was introduced in the following commit:
https://github.com/aerokube/selenoid-ui/commit/c5c4e428762653099ceb4b4a482f0b0bb393b708#diff-3495dc61525c7da7cab0f3ed0f2c215aR95

Is this a bug, or a feature? I can't see that it's documented anywhere in either the original PR, or the [changelog](https://github.com/aerokube/selenoid-ui/releases/tag/1.10.0) for version 1.10. The ability to delete 'stuck' sessions was something I found to be useful and consider this something of a regression.

If it's intended, then can I suggest introducing a flag / option to re-enable deletion of selenoid sessions? naturally, not all deployments will be exposed to non-administrators, and so there must be use cases for this functionality.

**Comment by vania-pooh** [comment]
@b71729 this is a feature to not accidentally remove automated sessions. But let's discuss how would you see this.

**Comment by lanwen** [comment]
There is an option to enable that deletion capability - just add manual label for the capabilities :) 
We can improve this maybe with some invisible or dedicated label - like "removable", or maybe some startup argument, which would add this label by default for all sessions to the output (ignoring the real label value)

**Comment by b71729** [comment]
I'd prefer a command line flag to the `selenoid-ui` binary if this functionality was intended, rather than requiring a change to the selenium capabilities. It's dependent on the specifics of the deployment after all.

I haven't contributed to this repo before; is this something you'd like to have implemented?
