### ISSUE TITLE
Error 404 page not found

### ISSUE THREAD

**Issue by MissiaL** [aerokube/selenoid-ui#39]
After launching the container with params:
`docker run -d --name selenoid-ui --net host aerokube/selenoid-ui`
When I try to go to the address `http://localhost:8080` I get an error `Error 404 page not found`
Why is this happening?

**Comment by vania-pooh** [comment]
@MissiaL what is your environment? Is any process listening on port 8080?

**Comment by SrinivasanTarget** [comment]
Facing same issue: 
Did started using ```docker run -d --name selenoid-ui -p 8080:8080 aerokube/selenoid-ui --selenoid-uri=http://172.17.0.2:4444```

http://172.17.0.2:4444 - selenoid host ip.

```
docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
93890fef68d9        aerokube/selenoid-ui   "/selenoid-ui --se..."   11 minutes ago      Up 11 minutes       0.0.0.0:8080->8080/tcp   selenoid-ui
479d84bea976        aerokube/selenoid      "/usr/bin/selenoid..."   2 hours ago         Up 2 hours          0.0.0.0:4444->4444/tcp   selenoid
```

**Comment by vania-pooh** [comment]
@MissiaL, @SrinivasanTarget I'm asking about environment because Docker on Windows \ Mac is in fact a virtual machine with Linux + smart port forwarding to this machine. Because of that `--net=host` does not work. You need to forward ports instead with `-p 8080:8080`. Let me check whether it works on latest containers...

**Comment by SrinivasanTarget** [comment]
@vania-pooh We are running docker containers inside a ubuntu machine. If you check above comments, i m actually doing port forwarding already.

**Comment by vania-pooh** [comment]
@SrinivasanTarget ok. Let me check then.

**Comment by SrinivasanTarget** [comment]
Sure @vania-pooh Between thanks for this awesome docker solution 👍

**Comment by vania-pooh** [comment]
@MissiaL, @SrinivasanTarget I managed to reproduce the issue - we broke something during the last release. Should work with release `aerokube/selenoid-ui:1.2.0`.

**Comment by SrinivasanTarget** [comment]
Cool will give a try and update back @vania-pooh

**Comment by lanwen** [comment]
Thanks for the report, will cover UI with integration tests for the `latest` tag too.
Stupid error in last commit -_-
