### ISSUE TITLE
When I execute .yml file getting below error message...

### ISSUE THREAD

**Issue by devendra-june-29** [aerokube/selenoid-ui#404]
Pulling selenoid (aerokube/selenoid:)...
latest: Pulling from aerokube/selenoid
188c0c94c7c5: Pull complete                                                                                                                                                                     7ec34015e55c: Pull complete                                                                                                                                                                     17819b3be777: Pull complete                                                                                                                                                                     Digest: sha256:0079b86b2dddc3e7360c19c4ee645e0ef3f52ab27caed4ee8986982557dba957
Status: Downloaded newer image for aerokube/selenoid:latest
Pulling selenoid-ui (aerokube/selenoid-ui:)...
latest: Pulling from aerokube/selenoid-ui
58fe8e792a7e: Pull complete                                                                                                                                                                     4cb0e8b6d528: Pull complete                                                                                                                                                                     2d1a4144a7d7: Pull complete                                                                                                                                                                     Digest: sha256:d99e3efddca4397f1cf38bfa5641e80094da43a152a7ae3866509e2258703a76
Status: Downloaded newer image for aerokube/selenoid-ui:latest
Creating newselenoid_selenoid_1 ... done                                                                                                                                                        Creating newselenoid_selenoid-ui_1 ... error                                                                                                                                                    
**_ERROR: for newselenoid_selenoid-ui_1  Cannot start service selenoid-ui: Cannot link to a non running container: /newselenoid_selenoid_1 AS /newselenoid_selenoid-ui_1/newselenoid_selenoid_1

ERROR: for selenoid-ui  Cannot start service selenoid-ui: Cannot link to a non running container: /newselenoid_selenoid_1 AS /newselenoid_selenoid-ui_1/newselenoid_selenoid_1
ERROR: Encountered errors while bringing up the project._**

yml file
version: '3'
services:
  selenoid:
   network_mode: bridge
   image: aerokube/selenoid
   volumes:
     - "G:/Selenoid/newselenoid:/etc/selenoid"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "G:/Selenoid/newselenoid/video:/opt/selenoid/video"
   environment:
     - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenium/video
     - TZ=Europe/Amsterdam
   command: -listen :4444 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -timeout 3m -limit 10

   ports:
     - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]   

browser.json file
{
    "firefox": {
        "default": "57.0",
        "versions": {
            "57.0": {
                "image": "selenoid/vnc:firefox_57.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        },
        "versions": {
            "83.0": {
                "image": "selenoid/vnc:firefox_83.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        },

        "versions": {
            "80.0": {
                "image": "selenoid/vnc:firefox_80.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    },

    "chrome": {
        "default": "64.0",
        "versions": {
            "64.0": {
                "image": "selenoid/vnc:chrome_64.0",
                "port": "4444",
                "path": "/"
            }
        },
        "versions": {
            "87.0": {
                "image": "selenoid/vnc:chrome_87.0",
                "port": "4444",
                "path": "/"
            }
        },

        "versions": {
            "85.0": {
                "image": "selenoid/vnc:chrome_85.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}

Please suggest.

**Comment by vania-pooh** [comment]
@devendra-june-29 Selenoid does not start for some reason and you get this error. Check Selenoid logs first with `docker logs selenoid`.

**Comment by devendra-june-29** [comment]
When I execute docker logs selenoid
getting an error : Error: No such container: selenoid

**Comment by vania-pooh** [comment]
@devendra-june-29 please use correct container name instead.
