### ISSUE TITLE
New Feature Enhancement Request - Selenoid UI with Keycloak Authentication

### ISSUE THREAD

**Issue by surevs** [aerokube/selenoid-ui#407]
Hi, 
Firstly Thanks so much for an amazing project of Selenoid-UI which has most of the cool interactions in place in much simplified manners and must say thing called - "Coolest UX"

I did go through configuring the basic authentication mechanism which exists as on today using nginx - https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/ 

It would be quite effective to integrate with [keycloak](https://www.keycloak.org/)  as it gives us with more robust way of controls and also helps us with user federation too.

Please let us know if there are any nearby plans of implementing this feature request.

Thanks a ton in anticipation.

Regards, Revant

**Comment by vania-pooh** [comment]
@surevs this is not in our nearby plans.

**Comment by surevs** [comment]
sure, thanks for the quick response
