### ISSUE TITLE
events not connected regularly in selenoid UI

### ISSUE THREAD

**Issue by dutchview-harsha** [aerokube/selenoid-ui#412]
HI @vania-pooh I am using selenoid ui and out of 10 events call one will be work/pass and 9 will be failed. 
i am using ngnix proxy layer 

can you please guide me :

server {
    listen 80;
    server_name selenoid.internaldomain.com;
    return 301 https://$host$request_uri;
}
upstream tool-server-selenoid {
    server #######:4444;
    keepalive 20;
}
upstream tool-server-selenoid-ui {
    server #####:8082;
    keepalive 20;
}
server {
    client_max_body_size 20M;
    #location / {
    #include /etc/nginx/auth/common.conf;
        #proxy_set_header Connection "";
        #proxy_buffering off;
        #proxy_http_version 1.1;
        #proxy_pass http://######:8082;
    #proxy_set_header X-Forwarded-Proto $scheme;
        #proxy_set_header X-Forwarded-Host $host;
        #proxy_set_header X-Forwarded-Server $host;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #}
    # selenoid-ui
    location / {
       proxy_pass http://tool-server-selenoid-ui;
       include /etc/nginx/auth/common.conf;
    }
    # selenoid backend - hub
    location /wd {
       proxy_pass http://tool-server-selenoid;
    }
    # selenoid backend - wss
    location /ws {
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header Host $host;
       proxy_pass http://tool-server-selenoid-ui;
       proxy_http_version 1.1;
       proxy_read_timeout 3600s;
       proxy_send_timeout 3600s;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
    }
    #location /status {
    #   proxy_pass http://tool-server-selenoid;
    #}
    location /video {
       proxy_pass http://tool-server-selenoid;
    }
    location /logs {
       proxy_pass http://tool-server-selenoid;
    }
    location /download {
       proxy_pass http://tool-server-selenoid;
    }
    location /clipboard {
       proxy_pass http://tool-server-selenoid;
    }
    location /devtools {
       proxy_pass http://tool-server-selenoid;
    }
    location /vnc {
      proxy_pass http://tool-server-selenoid;
    }
    location /ping {
       proxy_pass http://tool-server-selenoid;
    }
    location /events {
       proxy_pass http://tool-server-selenoid-ui;
    }

 
}
<img width="1786" alt="Screenshot 2021-02-10 at 4 38 40 PM" src="https://user-images.githubusercontent.com/45383305/107502268-77097980-6bbe-11eb-8993-a686ec905ee9.png">

**Comment by vania-pooh** [comment]
@dutchview-harsha try to increase max request timeout as events are using long-running HTTP requests.

**Comment by dutchview-harsha** [comment]
@vania-pooh I added below 

Proxy_connect_timeout 60;
proxy_send_timeout 300;
proxy_read_timeout 300;

Doesn't help

**Comment by harsha-google** [comment]
@vania-pooh Even i am facing same issue any updates or workaround ??

**Comment by vania-pooh** [comment]
@dutchview-harsha I would take a look at browser console errors then.

**Comment by harsha-google** [comment]
I dint see any console errors 
<img width="1762" alt="Screenshot 2021-02-15 at 11 38 44 AM" src="https://user-images.githubusercontent.com/63581994/107911376-79831f00-6f82-11eb-8365-d4b0f6a96f05.png">

**Comment by vania-pooh** [comment]
@dutchview-harsha you should. Try to reload the page.

**Comment by dutchview-harsha** [comment]
@vania-pooh tried several times didn't seen any errors. can you please send me sample nginx configuration

**Comment by vania-pooh** [comment]
@dutchview-harsha try to add the same headers for `/events` like you did for `/ws`.
