### ISSUE TITLE
Selenoid ui basic auth wss problem

### ISSUE THREAD

**Issue by clicman** [aerokube/selenoid-ui#419]
Hi! Covered selenoid UI endpoint by basic auth on apache proxy side and got problem with wss connection. It fails with 401 error in the developer console. How to pass it?

**Comment by vania-pooh** [comment]
@clicman how about http://aerokube.com/selenoid-ui/latest/#_restricting_access ?

**Comment by clicman** [comment]
Ohh. Yep! Will try it.
