### ISSUE TITLE
Is selenoid UI supported for arm processor.?

### ISSUE THREAD

**Issue by Kiran2205** [aerokube/selenoid-ui#443]
I am looking to install the Selenoid UI image for macbook m1, but unable to find the supported image.

**Comment by vania-pooh** [comment]
@Kiran2205 we actually don't build our source code for ARM, however Selenoid UI is Golang-based and Golang allows to build for this architecture. But the main problem is that our browser images are currently not compatible with ARM (because browser binaries are built for x86).

**Comment by Juice10** [comment]
> @Kiran2205 we actually don't build our source code for ARM, however Selenoid UI is Golang-based and Golang allows to build for this architecture. But the main problem is that our browser images are currently not compatible with ARM (because browser binaries are built for x86).

This should become a lot easier to support (for the playwright browser images) with playwright 1.16: https://github.com/microsoft/playwright/issues/7723#issuecomment-940484673

**Comment by vania-pooh** [comment]
Binary support for ARM was added in https://github.com/aerokube/selenoid-ui/pull/486. We may also consider building a Docker image for ARM64 but this will require using `docker buildx`.

**Comment by aandryashin** [comment]
Please consider this:

https://github.com/aandryashin/moon-on-apple-silicon

There are images built for selenium and playwright, and detailed
instruction.

пн, 20 июн. 2022 г., 11:25 Ivan Krutov ***@***.***>:
