### ISSUE TITLE
installation Selenoid using binary

### ISSUE THREAD

**Issue by ghost** [aerokube/selenoid-ui#447]
I have installed selenoid using binary but selenoid UI is not working using binary not able to established connection. It gives error .

**Comment by varshabhijeet** [comment]
![image](https://user-images.githubusercontent.com/47491842/128672046-7ca6b28b-0e34-4bbc-b978-8527fa011012.png)

**Comment by vania-pooh** [comment]
@varshabhijeet check that you provided correct `--selenoid-uri` flag value pointing to Selenoid host and port.

**Comment by varshabhijeet** [comment]
i have passed correct url 
![image](https://user-images.githubusercontent.com/47491842/128702570-b2a65535-ce07-448e-bb01-c0cf5da5552c.png)
by using ./selenoid-ui_linux_amd64 -listen :9000  --selenoid-uri http://3.138.61.255:4444/ this command i have stated  selenoid ui

**Comment by varshabhijeet** [comment]
![image](https://user-images.githubusercontent.com/47491842/128702795-112e8d30-3d29-45c4-a0bf-5c037aa4562f.png)

**Comment by varshabhijeet** [comment]
![image](https://user-images.githubusercontent.com/47491842/128702860-fab9a97c-6c3f-4464-adf0-65d5cacb79bc.png)

**Comment by vania-pooh** [comment]
@vania-pooh then open browser developer tools and find POST request to create a new session. You will see an exact error message.
