### ISSUE TITLE
UIData refresh

### ISSUE THREAD

**Issue by SrinivasanTarget** [aerokube/selenoid-ui#45]
@vania-pooh I did tried 1.2.0 as you said but the data is not turning up in UI during the execution.

<img width="1279" alt="screen shot 2017-06-01 at 1 33 27 pm" src="https://cloud.githubusercontent.com/assets/8896549/26670411/26275522-46cf-11e7-94ad-7a8675a86a75.png">

Execution was in progress but i dont see any data getting reflected in UI.

```
docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS              PORTS                    NAMES
f27d0a7a8da8        selenoid/chrome:58.0         "/bin/sh -c /entry..."   About a minute ago   Up 57 seconds       4444/tcp                 musing_feynman
5bc35661447a        selenoid/chrome:58.0         "/bin/sh -c /entry..."   About a minute ago   Up 57 seconds       4444/tcp                 quirky_hawking
81ebb48414c2        selenoid/chrome:58.0         "/bin/sh -c /entry..."   About a minute ago   Up 58 seconds       4444/tcp                 elegant_dubinsky
416fa082c2b9        selenoid/chrome:58.0         "/bin/sh -c /entry..."   About a minute ago   Up 58 seconds       4444/tcp                 tender_knuth
0b8089b54c3b        aerokube/selenoid-ui:1.2.0   "/selenoid-ui --se..."   5 minutes ago        Up 5 minutes        0.0.0.0:8080->8080/tcp   selenoid-ui
c6310479466a        aerokube/selenoid            "/usr/bin/selenoid..."   19 minutes ago       Up 19 minutes       0.0.0.0:4444->4444/tcp   selenoid
```

**Comment by vania-pooh** [comment]
@SrinivasanTarget both SSE and Selenoid indicators should be green. In your case Selenoid is red. I think this should mean that there is no access to Selenoid API.
@lanwen is my statement correct?

**Comment by vania-pooh** [comment]
@SrinivasanTarget btw, take a look at UI container logs. There should be error messages about access to Selenoid.

**Comment by lanwen** [comment]
Yep, if you see red - go to the logs.

**Comment by SrinivasanTarget** [comment]
@vania-pooh What's the solution?

**Comment by vania-pooh** [comment]
@SrinivasanTarget any error messages could help. But basically you need to correctly point UI to Selenoid as described here: http://aerokube.com/selenoid-ui/latest/#_you_have_docker

**Comment by SrinivasanTarget** [comment]
@vania-pooh I could not bash inside containers to retrieve logs. I see it is pointed to correct url that's why UI is rendered. Help me in fetching logs.

**Comment by aandryashin** [comment]
Please use this command to inspect logs of selenoid-ui container:

$ docker logs <selenoid-ui container id>

I think in your case the correct selenoid-uri option should be:

http://10.2341.207:4444

**Comment by lanwen** [comment]
Feel free to reopen if it still actual

**Comment by d-konovalov** [comment]
Hi guys
I can reproduce this issue
https://content.screencast.com/users/dmitrykonovalov/folders/Jing/media/b14e8e38-41ad-40f6-9a93-965d4b48830a/00000173.png
suppose I did something wrong

**Comment by lanwen** [comment]
@d-konovalov You should link your selenoid to selenoid-ui and use linked selenoid name as host.
Now in your selenoid-ui container nothing listens on :4444

**Comment by d-konovalov** [comment]
so I should use docker-compose for it, right?

**Comment by lanwen** [comment]
It's on your own, but it also possible with only `docker run -d --name selenoid-ui --link selenoid -p 8080:8080 aerokube/selenoid-ui --selenoid-uri=http://selenoid:4444`

**Comment by d-konovalov** [comment]
ah, now I see
sorry
and thank you, it works

**Comment by lanwen** [comment]
meh, found a bug with link - it uses same url for selenoid in browser to connect directly
