### ISSUE TITLE
restrict access

### ISSUE THREAD

**Issue by CraftedCat** [aerokube/selenoid-ui#481]
How to use cm with -users option?

 ./cm_linux_amd64 selenoid-ui start -users /etc/apache2/.htpasswd
Error: unknown shorthand flag: 'u' in -users

./cm_linux_amd64 selenoid-ui start -g -users /etc/apache2/.htpasswd
> Using Docker
- Your Docker API version is 1.41
> Selenoid UI is already downloaded
> Selenoid UI is already running
root@root:~/ms_ex_driver_sender# netstat -apn | grep 8080
clear...

**Comment by vania-pooh** [comment]
@CraftedCat this is only supported when starting UI manually. Don't try to use this flag with CM.
