### ISSUE TITLE
restrict access via htpasswd not working

### ISSUE THREAD

**Issue by cheesepaulo** [aerokube/selenoid-ui#492]
I`m doing something wrong?

`docker run -d -p 8080:8080 aerokube/selenoid-ui -users users.htpasswd`

Checking the logs I get.
`2022/08/06 00:52:00 [INIT] [Invalid users file: stat users.htpasswd: no such file or directory]`

The file is in the same directory where I am running the docker run command
I'm even using the same example from the documentation.

I generated the file with the command `htpasswd -bc users.htpasswd test-password`

**Comment by vania-pooh** [comment]
@cheesepaulo you obviously have to mount this file inside container with `-v` flag.
