### ISSUE TITLE
Is it possible somehow to run Safari on Windows/Linux?

### ISSUE THREAD

**Issue by VladyslavZagorodnyi** [aerokube/selenoid-ui#498]
I'm wondering if there is a possibility to run tests in Safari on Windows or Linux (Not Mac) machine? If you - pls provide an example.

**Comment by vania-pooh** [comment]
@VladyslavZagorodnyi no official Safari binaries for recent versions exist for Linux \ Windows. We have `browsers/safari` images built from WebKit source code (https://hub.docker.com/r/browsers/safari). This is not a true Safari but browser engine is the same.

**Comment by VladyslavZagorodnyi** [comment]
@vania-pooh , thanks, is there some guide which describe how to use it? (if yes, pls share)

**Comment by vania-pooh** [comment]
@VladyslavZagorodnyi you just add Safari images to `browsers.json` as other images like Chrome.

**Comment by VladyslavZagorodnyi** [comment]
@vania-pooh 
I added safari to browsers.json
![image](https://user-images.githubusercontent.com/29700638/195825269-72406348-c6d5-4484-8aee-6f0e99a9beb4.png)
but when I run tests I see this:
![image](https://user-images.githubusercontent.com/29700638/195825467-bd81f025-8149-4391-960b-6dbed77620a9.png)
maybe something is not correct?

**Comment by aandryashin** [comment]
Try to change path to "/".

пт, 14 окт. 2022 г., 13:27 Vladyslav Zagorodnyi ***@***.***>:

**Comment by aandryashin** [comment]
please change

"path": "/wd/hub" to "path": "/"

in browsers.json

пт, 14 окт. 2022 г., 13:40 Vladyslav Zagorodnyi ***@***.***>:

**Comment by VladyslavZagorodnyi** [comment]
@aandryashin 
Unfortunately nothing changed 
![image](https://user-images.githubusercontent.com/29700638/195867694-f69cc03c-cf72-4e80-b304-af8a13646b2a.png)

**Comment by vania-pooh** [comment]
@VladyslavZagorodnyi you should use RemoteWebDriver instead of SafariDriver.

**Comment by anilverma-070** [comment]
> @aandryashin Unfortunately nothing changed ![image](https://user-images.githubusercontent.com/29700638/195867694-f69cc03c-cf72-4e80-b304-af8a13646b2a.png)

You still need to revert back / prefixed to browser image name.
