### ISSUE TITLE
Starting manual session on selenoid-ui fails after restricting access to selenoid ui.

### ISSUE THREAD

**Issue by soumyathampi** [aerokube/selenoid-ui#516]
I have restricted user access to selenoid-ui by following https://aerokube.com/selenoid-ui/latest/#_restricting_access.

Able to start session succesfully using automation and curl commands. But I\not able to start a session manually from the selenoid-ui.

response: 
status: 
13
value: 
message: 
"unsupported browser: chrome-110.0 manual=true"

**Comment by vania-pooh** [comment]
@soumyathampi you just don't have this browser version in `browsers.json`.

**Comment by soumyathampi** [comment]
THis works fine with curl command:
curl -H'Content-Type: application/json' http://10.1.121.94:4444/wd/hub/session -d'{
    "capabilities": {
        "alwaysMatch": {
            "browserName": "chrome",
            "browserVersion": "110.0",
            "selenoid:options": {
                "name": "Session started using curl command...",
                "sessionTimeout": "1m"
            }
        }
    }
}'
Only manual session fails to start.

**Comment by vania-pooh** [comment]
@soumyathampi when using Ggr you may be redirected to the host where you don't have this version.

**Comment by soumyathampi** [comment]
I have 2 instances connected to this ggr, both works fine. But the issue comes from selenoid.

Getting this error on my console while starting the session:
POST http://10.1.121.94:8080/wd/hub/session 404 (Not Found)
VM12:24 Can't start session manually e {message: 'ajax error 404', name: 'AjaxError', xhr: XMLHttpRequest, request: {…}, status: 404, …}

**Comment by soumyathampi** [comment]
Which version should we use?

**Comment by vania-pooh** [comment]
@soumyathampi e.g. `aerokube/ggr-ui:1.1.2` or `aerokube/ggr-ui:latest-release`.

**Comment by soumyathampi** [comment]
I am already using ggr-ui:latest-release, hardcoding to 1.1.2 also didn't fix this issue

**Comment by vania-pooh** [comment]
@soumyathampi check logs of all these containers.
