### ISSUE TITLE
Copy File layer Vulnerability

### ISSUE THREAD

**Issue by Dor-bl** [aerokube/selenoid-ui#518]
Hi!

where is the correct place to update the stdlib version ?
![image](https://github.com/aerokube/selenoid-ui/assets/59066376/c6da17f8-03b2-492d-95cb-9f532135c63e)

**Comment by vania-pooh** [comment]
@Dor-bl I think we need to update Golang version.

**Comment by Dor-bl** [comment]
@vania-pooh thanks for the quick update. When do you think you can release a new version?

**Comment by vania-pooh** [comment]
@Dor-bl will do during next few days.
