### ISSUE TITLE
Doesn't work on M1

### ISSUE THREAD

**Issue by EkaterynaRuslanovna** [aerokube/selenoid-ui#522]
![image](https://github.com/aerokube/selenoid-ui/assets/131962234/459a52e3-afae-4423-8c28-9ea3d0a5a64e)

I do everything according to the instructions, but there is no connection of the selenoid.

**Comment by vania-pooh** [comment]
@EkaterynaRuslanovna please take a look at UI container logs first. But it seems that there is no connection to Selenoid.

**Comment by EkaterynaRuslanovna** [comment]
<img width="1206" alt="image" src="https://github.com/aerokube/selenoid-ui/assets/131962234/a15e645a-66c5-41e6-a89a-648674db5010">
😔

**Comment by EkaterynaRuslanovna** [comment]
Sorry, it finally worked🥰
