### ISSUE TITLE
[Proposal] Selenoid/ggr UI should provide notifications for updates available for themselves and browser images

### ISSUE THREAD

**Issue by c0dehu1k** [aerokube/selenoid-ui#523]
Idea is to notify user about the selenoid ui/ggr updates are available.
This can be extended to browser images as well.

**Comment by vania-pooh** [comment]
@c0dehu1k it makes no sense as you can subscribe to Github releases where this is already implemented.

**Comment by c0dehu1k** [comment]
@vania-pooh ok!
But what about the browser images
e.g. i have Chrome 110 installed and chrome110 got updated..

Note browser images which I am currently using in selenoid..

**Comment by vania-pooh** [comment]
@c0dehu1k this will anyway require updating `browsers.json` and using latest images in `browsers.json` is available in cm tool.

**Comment by c0dehu1k** [comment]
ok @vania-pooh!!
