### ISSUE TITLE
Layout issues on small screens

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid-ui#71]
When VNC session is disconnected its buttons oveflow logs window. 13" Mac OS 10.12 Firefox 55.0.2.
<img width="888" alt="screen shot 2017-08-19 at 12 43 47" src="https://user-images.githubusercontent.com/829320/29485564-6012a714-84dc-11e7-8f33-984def357b68.png">

**Comment by lanwen** [comment]
Cool. Will try place both blocks side-by-side to avoid such things

**Comment by temagi** [comment]
There is also issue with "name" layout on Windows 10: FF 54.0.1 and Chrome 60
![screenshot_1](https://user-images.githubusercontent.com/1005801/29511512-92e9e2c0-8689-11e7-9f12-15d8a0f15ba8.png)

**Comment by lanwen** [comment]
on ff 54 first problem is not reproducible o_O

**Comment by vania-pooh** [comment]
Hm, cannot reproduce myself now. So you can close when done with side-by-side view.

**Comment by lanwen** [comment]
Should be fixed in #75
