### ISSUE TITLE
Add possibility to specify port number when run selenoid-ui through Configuration Manager

### ISSUE THREAD

**Issue by slipwalker** [aerokube/selenoid-ui#79]
It would be useful to have possibility to override default port that selenoid-ui is going to start on. I mean something like that:
```
./cm selenoid-ui start -p 8090.
```
Or if it already is, please advise how to do that when using Configuration Manager. Thanks in advance.

**Comment by lanwen** [comment]
`./cm selenoid-ui start --args "-listen :8090"`

**Comment by slipwalker** [comment]
Thanks for suggestion, but it doesn't look working, cause selenoid-ui page neither opened by localhost:8080 nor localhost:8090 in this case. Also docker ps returns following:

```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                    NAMES
6fb504e8a3bc        aerokube/selenoid-ui:latest   "/selenoid-ui -lis..."   3 minutes ago       Up 3 minutes        0.0.0.0:8080->8080/tcp   selenoid-ui

```

**Comment by vania-pooh** [comment]
With current release of `cm` this will not work because forwarded port number is hard-coded to `cm` (used to determine whether container is already running). However I'm not sure whether we should implement it. `cm` main purpose is to deliver working solution with minimum configuration. I think customizing UI port could be done by starting it manually. In `selenoid-ui` [documentation](http://aerokube.com/selenoid-ui/latest/) we give an exact Docker command that could be used to start `selenoid-ui` manually.

@lanwen any ideas?

**Comment by lanwen** [comment]
It's not very hard to run UI with separate command if you need custom port. Just type `./selenoid-ui --listen :8090 --selenoid-uri 'http://<where-selenoid-is>:><4444 (or your port)>`

Same as with cm in this case

**Comment by Lucifar2** [comment]
@lanwen Is there any way to create multiple selenoid instances with different ports on same machine ? I need to create 1 instance in port 8080 and lets say another one on port 8081

**Comment by vania-pooh** [comment]
@Lucifar2 use `-listen` flag.

**Comment by Lucifar2** [comment]
@vania-pooh Thanks for the reply. I used the following command on windows : 
cm selenoid start --args "-listen 8081" (I wanted to use the new instance of selenoid on 8081)
It returns me the below : 
> Using Docker
- Your Docker API version is 1.41
> Selenoid is already downloaded
> Selenoid is already configured
> Selenoid is already running

When I try to open my selenoid instance on localhost:8081 it never opens. I have already tried to start the UI on the port as well.

**Comment by vania-pooh** [comment]
@Lucifar2 this can be done when starting everything manually only. With CM it will always bind port 8080/

**Comment by Lucifar2** [comment]
@vania-pooh Thanks. I was able to do it successfully. I had to link the selenoid with the selenoid UI manually. 
Is there a way to do it with ./cm selenoid start --port 8686 ... something like this ?

**Comment by lanwen** [comment]
@Lucifar2 cm is supposed to be a quick-start tool. If you want something custom - better to use binaries directly
