### ISSUE TITLE
Add an ability to distinguish runned browsers

### ISSUE THREAD

**Issue by ElijahCapricorn** [aerokube/selenoid-ui#86]
When Selenoid runs several containers at the same time Selenoid-UI shows this containers as similar blocks. 
![image](https://user-images.githubusercontent.com/7524899/32279564-2997ad64-bf2a-11e7-9ed8-08eb80dfc49d.png)
It's hard to understand where is needed test is run.
So, I offer to add new capability to Selenoid. Something like this:
```
{
    "browserName": ...
    "selenoidLabel": "TestLogOnWithRightCredentials"
}
```
![image](https://user-images.githubusercontent.com/7524899/32280173-08312d88-bf2c-11e7-8906-bc69832ebb6f.png)

**Comment by vania-pooh** [comment]
@ElijahCapricorn just pass an additional capability...
```
name: my-custom-test-tag
```
... and you will see an additional tag on the rectangle.

**Comment by vania-pooh** [comment]
Here are the docs about it: http://aerokube.com/selenoid/latest/#_custom_test_name

**Comment by ElijahCapricorn** [comment]
@vania-pooh oh, sorry. I didn't see this when was reading documentation. Thanks for your reply.
