### ISSUE TITLE
Add VNC read-only mode support to UI

### ISSUE THREAD

**Issue by vania-pooh** [aerokube/selenoid-ui#96]
As described.

**Comment by janwiemers** [comment]
Hey there, just stumbled upon this. That would be particularly useful in my usecase. Is there any update? I would like to prevent users clicking by any means :)

Thanks for this great piece of software

**Comment by vania-pooh** [comment]
@janwiemers this will be implemented soon. Unfortunately can't give any definitive date. But this should be one of the next features to be added to UI.
