### ISSUE TITLE
Canvas for VNC do not fill whole browser viewport

### ISSUE THREAD

**Issue by baranoff-ivan** [aerokube/selenoid-ui#97]
When I maximize view with VNC session in my browser (Chrome or Firefox on Windows 7), it does not fill whole browser viewport.
While canvas width and height are properly set to 1920 and 1080 respectively, style's width and height are 
1122px and 631px:
`<canvas width="1920" height="1080" style="width: 1122px; height: 631px; cursor: default;">Canvas not supported.</canvas>`
As a result I see something like this:
![image](https://user-images.githubusercontent.com/17180401/35970734-82b403ca-0cdc-11e8-97aa-e6d8366288dc.png)

Any suggestions on how to solve my problem?

**Comment by lanwen** [comment]
Probably same problem as in #76

**Comment by vania-pooh** [comment]
Closing as duplicate then.
