### ISSUE TITLE
support of locale ru_RU.UTF-8

### ISSUE THREAD

**Issue by me1ram** [aerokube/selenoid-ui#98]
Inside the selenoid-ui in log window I can not see russian locale
Try to open yandex.ru and try to print the title.
The container of browser is ok.

Can you fix it?

**Comment by lanwen** [comment]
Probably should use https://www.npmjs.com/package/utf8 to decode log stream

**Comment by me1ram** [comment]
I used Python.
with 
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```
