### ISSUE TITLE
Support of wss connections

### ISSUE THREAD

**Issue by alexandrvb** [aerokube/selenoid-ui#99]
We want to use nginx proxy with ssl termination but it seems that selenoid-ui doesn't support of secure websockets. I have the following error in console:
```
Failed when connecting: Error while connecting (SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.)
```

**Comment by lanwen** [comment]
ws now hardcoded here: 
https://github.com/aerokube/selenoid-ui/blob/master/web/src/components/Log/index.js#L53

and here:
https://github.com/aerokube/selenoid-ui/blob/master/web/src/components/VncCard/VncScreen.js#L66
If you have any thought on how to make it customizable, you are welcome ;)

**Comment by nicolastorres** [comment]
@alexandrvb Do you mind posting the nginx configuration? I couldn´t make it work behind an nginx proxy.
Thanks
